# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish

on:
  push:
    branches:
      - ci/publishing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: yarn install
      - run: yarn add -D node-sass

      - name: Test Dart Sass
        run: node test/dart-sass/dart-sass.js
      - name: Test Node Sass
        run: node test/node-sass/node-sass.js

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
        run: yarn install

      - run: git config --global user.email "Daniil Chudo"
      - run: git config --global user.name "daniil4udo@gmail.com"
      - run: git fetch --tags

      - name: Publishing
        run: lerna publish from-package --yes --no-verify-access
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTOMATION_TOKEN}}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/

      - name: Install Dependencies
        run: yarn install

      - name: Fetch Git tags
        run: git fetch --tags

      - name: Publishing
        run: lerna publish from-package --yes --no-verify-access
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}